import type { Metadata } from "next";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex gap-x-3 lg:gap-x-5 p-2 lg:p-5 h-screen">
      <Navbar />
      <div className="flex-1">{children}</div>
    </div>
  );
}
