import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Weather Pulse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="max-w-[1500px] mx-auto">{children}</body>
    </html>
  );
}
